import 'package:flutter/painting.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:smarttube_poc/domain/entities/media_subtitle.dart';
import 'package:smarttube_poc/presentation/screens/player/subtitle_styles.dart';

MediaSubtitle sub(String code, {bool auto = false}) => MediaSubtitle(
      code: code,
      name: code,
      url: 'https://example.test/$code${auto ? '-auto' : ''}.vtt',
      isAutoGenerated: auto,
    );

void main() {
  group('subtitleStyleSpec', () {
    test('white presets differ only in their background', () {
      final plain = subtitleStyleSpec(SubtitleStyle.white);
      final boxed = subtitleStyleSpec(SubtitleStyle.whiteOnBlack);

      expect(plain.textColor, subtitleWhite);
      expect(boxed.textColor, subtitleWhite);
      expect(plain.backgroundColor.a, 0);
      expect(boxed.backgroundColor, const Color(0xFF000000));
      expect(plain.edge, SubtitleEdge.dropShadow);
      expect(boxed.edge, SubtitleEdge.outline);
    });

    test('yellow presets mirror the white ones', () {
      final plain = subtitleStyleSpec(SubtitleStyle.yellow);
      final boxed = subtitleStyleSpec(SubtitleStyle.yellowOnBlack);

      expect(plain.textColor, subtitleYellow);
      expect(boxed.textColor, subtitleYellow);
      expect(plain.backgroundColor.a, 0);
      expect(boxed.backgroundColor, const Color(0xFF000000));
      expect(plain.edge, SubtitleEdge.dropShadow);
      expect(boxed.edge, SubtitleEdge.outline);
    });

    test('only the custom preset follows the opacity slider', () {
      final custom = subtitleStyleSpec(
        SubtitleStyle.custom,
        customBackgroundOpacity: 0.25,
      );
      expect(custom.backgroundColor.a, closeTo(0.25, 0.01));

      final fixed = subtitleStyleSpec(
        SubtitleStyle.whiteOnBlack,
        customBackgroundOpacity: 0.25,
      );
      expect(fixed.backgroundColor, const Color(0xFF000000));
    });

    test('an out-of-range custom opacity is clamped', () {
      expect(
        subtitleStyleSpec(
          SubtitleStyle.custom,
          customBackgroundOpacity: 4,
        ).backgroundColor.a,
        1,
      );
      expect(
        subtitleStyleSpec(
          SubtitleStyle.custom,
          customBackgroundOpacity: -1,
        ).backgroundColor.a,
        0,
      );
    });
  });

  group('edge shadows', () {
    test('a drop shadow is one blurred copy', () {
      final shadows = subtitleEdgeShadows(SubtitleEdge.dropShadow);
      expect(shadows, hasLength(1));
      expect(shadows.single.blurRadius, greaterThan(0));
      expect(shadows.single.color, const Color(0xFF000000));
    });

    test('an outline is four sharp copies around the glyph', () {
      final shadows = subtitleEdgeShadows(SubtitleEdge.outline);
      expect(shadows, hasLength(4));
      expect(shadows.every((s) => s.blurRadius == 0), isTrue);
      expect(
        shadows.map((s) => s.offset.dx.sign).toSet(),
        {-1.0, 1.0},
      );
      expect(
        shadows.map((s) => s.offset.dy.sign).toSet(),
        {-1.0, 1.0},
      );
    });
  });

  group('subtitleViewConfigurationFor', () {
    test('carries colours, scale and padding into media_kit', () {
      final config = subtitleViewConfigurationFor(
        SubtitleStyle.yellowOnBlack,
        scale: 1.5,
        bottomPadding: 64,
        horizontalPadding: 16,
      );

      expect(config.style.color, subtitleYellow);
      expect(config.style.backgroundColor, const Color(0xFF000000));
      expect(config.style.fontSize, subtitleBaseFontSize * 1.5);
      expect(config.style.shadows, hasLength(4));
      expect(config.padding, const EdgeInsets.fromLTRB(16, 0, 16, 64));
    });

    test('the default preset keeps the pre-presets look', () {
      final config = subtitleViewConfigurationFor(SubtitleStyle.defaultStyle);
      expect(config.style.color, const Color(0xFFFFFFFF));
      expect(config.style.fontSize, subtitleBaseFontSize);
      expect(config.style.backgroundColor?.a, closeTo(0.67, 0.01));
    });

    test('every preset produces a usable configuration', () {
      for (final style in SubtitleStyle.values) {
        final config = subtitleViewConfigurationFor(style);
        expect(config.style.color, isNotNull, reason: style.name);
        expect(config.style.shadows, isNotEmpty, reason: style.name);
      }
    });
  });

  group('subtitleStyleFromName', () {
    test('round-trips every preset', () {
      for (final style in SubtitleStyle.values) {
        expect(subtitleStyleFromName(style.name), style);
      }
    });

    test('unknown and missing names fall back to the default', () {
      expect(subtitleStyleFromName(null), SubtitleStyle.defaultStyle);
      expect(subtitleStyleFromName('neon'), SubtitleStyle.defaultStyle);
    });
  });

  group('resolvePreferredSubtitleLanguage', () {
    test('"app" follows the app language', () {
      expect(
        resolvePreferredSubtitleLanguage(
          appDefaultSubtitleLanguage,
          appLanguage: 'ar',
          deviceLanguage: 'en',
        ),
        'ar',
      );
    });

    test('"app" falls through to the device when the app follows it', () {
      expect(
        resolvePreferredSubtitleLanguage(
          appDefaultSubtitleLanguage,
          appLanguage: 'system',
          deviceLanguage: 'fr',
        ),
        'fr',
      );
    });

    test('"off" disables automatic selection', () {
      expect(
        resolvePreferredSubtitleLanguage(
          noPreferredSubtitleLanguage,
          appLanguage: 'ar',
          deviceLanguage: 'ar',
        ),
        isNull,
      );
    });

    test('an explicit language wins over both', () {
      expect(
        resolvePreferredSubtitleLanguage(
          'en',
          appLanguage: 'ar',
          deviceLanguage: 'ar',
        ),
        'en',
      );
    });
  });

  group('pickPreferredSubtitle', () {
    test('prefers a human track over the auto-generated one', () {
      final picked = pickPreferredSubtitle(
        [sub('en', auto: true), sub('en'), sub('ar')],
        'en',
      );
      expect(picked?.code, 'en');
      expect(picked?.isAutoGenerated, isFalse);
    });

    test('prefers an exact code over a regional variant', () {
      final picked = pickPreferredSubtitle(
        [sub('en-GB'), sub('en')],
        'en',
      );
      expect(picked?.code, 'en');
    });

    test('accepts a regional variant when nothing else matches', () {
      final picked = pickPreferredSubtitle(
        [sub('fr'), sub('en_US', auto: true), sub('en-GB')],
        'en',
      );
      expect(picked?.code, 'en-GB');
    });

    test('is case insensitive', () {
      expect(pickPreferredSubtitle([sub('EN')], 'en')?.code, 'EN');
    });

    test('returns null when the language is absent or unset', () {
      expect(pickPreferredSubtitle([sub('ar')], 'en'), isNull);
      expect(pickPreferredSubtitle([sub('ar')], null), isNull);
      expect(pickPreferredSubtitle([sub('ar')], ''), isNull);
      expect(pickPreferredSubtitle([], 'ar'), isNull);
    });

    test('does not match a language that merely starts the same', () {
      expect(pickPreferredSubtitle([sub('english')], 'en'), isNull);
    });
  });
}
