// ============================================================
// MediaSubtitle - Freezed entity (FIXED: removed invalid part directives)
// ============================================================
// تم نقل ChapterItem, SponsorSegment, DeArrowData إلى ملفاتها الخاصة.
// هذا الملف يحتوي على MediaSubtitle فقط.
// ============================================================

import 'package:freezed_annotation/freezed_annotation.dart';

part 'media_subtitle.freezed.dart';

@freezed
class MediaSubtitle with _$MediaSubtitle {
  const factory MediaSubtitle({
    required String code, // e.g., "ar", "en"
    required String name, // e.g., "Arabic", "English (auto-generated)"
    required String url,
    @Default(false) bool isAutoGenerated,
  }) = _MediaSubtitle;
}
