// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'media_subtitle.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more information: https://github.com/rrousselGit/freezed#adding-getters-and-methods-to-our-models');

/// @nodoc
mixin _$MediaSubtitle {
  String get code => throw _privateConstructorUsedError; // e.g., "ar", "en"
  String get name =>
      throw _privateConstructorUsedError; // e.g., "Arabic", "English (auto-generated)"
  String get url => throw _privateConstructorUsedError;
  bool get isAutoGenerated => throw _privateConstructorUsedError;

  /// Create a copy of MediaSubtitle
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  $MediaSubtitleCopyWith<MediaSubtitle> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $MediaSubtitleCopyWith<$Res> {
  factory $MediaSubtitleCopyWith(
          MediaSubtitle value, $Res Function(MediaSubtitle) then) =
      _$MediaSubtitleCopyWithImpl<$Res, MediaSubtitle>;
  @useResult
  $Res call({String code, String name, String url, bool isAutoGenerated});
}

/// @nodoc
class _$MediaSubtitleCopyWithImpl<$Res, $Val extends MediaSubtitle>
    implements $MediaSubtitleCopyWith<$Res> {
  _$MediaSubtitleCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  /// Create a copy of MediaSubtitle
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? code = null,
    Object? name = null,
    Object? url = null,
    Object? isAutoGenerated = null,
  }) {
    return _then(_value.copyWith(
      code: null == code
          ? _value.code
          : code // ignore: cast_nullable_to_non_nullable
              as String,
      name: null == name
          ? _value.name
          : name // ignore: cast_nullable_to_non_nullable
              as String,
      url: null == url
          ? _value.url
          : url // ignore: cast_nullable_to_non_nullable
              as String,
      isAutoGenerated: null == isAutoGenerated
          ? _value.isAutoGenerated
          : isAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$MediaSubtitleImplCopyWith<$Res>
    implements $MediaSubtitleCopyWith<$Res> {
  factory _$$MediaSubtitleImplCopyWith(
          _$MediaSubtitleImpl value, $Res Function(_$MediaSubtitleImpl) then) =
      __$$MediaSubtitleImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call({String code, String name, String url, bool isAutoGenerated});
}

/// @nodoc
class __$$MediaSubtitleImplCopyWithImpl<$Res>
    extends _$MediaSubtitleCopyWithImpl<$Res, _$MediaSubtitleImpl>
    implements _$$MediaSubtitleImplCopyWith<$Res> {
  __$$MediaSubtitleImplCopyWithImpl(
      _$MediaSubtitleImpl _value, $Res Function(_$MediaSubtitleImpl) _then)
      : super(_value, _then);

  /// Create a copy of MediaSubtitle
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? code = null,
    Object? name = null,
    Object? url = null,
    Object? isAutoGenerated = null,
  }) {
    return _then(_$MediaSubtitleImpl(
      code: null == code
          ? _value.code
          : code // ignore: cast_nullable_to_non_nullable
              as String,
      name: null == name
          ? _value.name
          : name // ignore: cast_nullable_to_non_nullable
              as String,
      url: null == url
          ? _value.url
          : url // ignore: cast_nullable_to_non_nullable
              as String,
      isAutoGenerated: null == isAutoGenerated
          ? _value.isAutoGenerated
          : isAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool,
    ));
  }
}

/// @nodoc

class _$MediaSubtitleImpl implements _MediaSubtitle {
  const _$MediaSubtitleImpl(
      {required this.code,
      required this.name,
      required this.url,
      this.isAutoGenerated = false});

  @override
  final String code;
// e.g., "ar", "en"
  @override
  final String name;
// e.g., "Arabic", "English (auto-generated)"
  @override
  final String url;
  @override
  @JsonKey()
  final bool isAutoGenerated;

  @override
  String toString() {
    return 'MediaSubtitle(code: $code, name: $name, url: $url, isAutoGenerated: $isAutoGenerated)';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$MediaSubtitleImpl &&
            (identical(other.code, code) || other.code == code) &&
            (identical(other.name, name) || other.name == name) &&
            (identical(other.url, url) || other.url == url) &&
            (identical(other.isAutoGenerated, isAutoGenerated) ||
                other.isAutoGenerated == isAutoGenerated));
  }

  @override
  int get hashCode =>
      Object.hash(runtimeType, code, name, url, isAutoGenerated);

  /// Create a copy of MediaSubtitle
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  @pragma('vm:prefer-inline')
  _$$MediaSubtitleImplCopyWith<_$MediaSubtitleImpl> get copyWith =>
      __$$MediaSubtitleImplCopyWithImpl<_$MediaSubtitleImpl>(this, _$identity);
}

abstract class _MediaSubtitle implements MediaSubtitle {
  const factory _MediaSubtitle(
      {required final String code,
      required final String name,
      required final String url,
      final bool isAutoGenerated}) = _$MediaSubtitleImpl;

  @override
  String get code; // e.g., "ar", "en"
  @override
  String get name; // e.g., "Arabic", "English (auto-generated)"
  @override
  String get url;
  @override
  bool get isAutoGenerated;

  /// Create a copy of MediaSubtitle
  /// with the given fields replaced by the non-null parameter values.
  @override
  @JsonKey(includeFromJson: false, includeToJson: false)
  _$$MediaSubtitleImplCopyWith<_$MediaSubtitleImpl> get copyWith =>
      throw _privateConstructorUsedError;
}
