// ============================================================
// SmartTube Mobile - Main Entry Point (FIXED: l10n delegates + AppThemeMode mapping)
// ============================================================

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:media_kit/media_kit.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Generated by flutter_localizations generator
import 'l10n/app_localizations.dart';

import 'data/local/preferences/settings_repository_impl.dart';
import 'presentation/l10n/locale_preference.dart';
import 'presentation/providers/player_providers.dart';
import 'presentation/providers/repository_providers.dart';
import 'presentation/providers/settings_providers.dart';
import 'presentation/routing/app_router.dart';
import 'presentation/theme/app_theme.dart';
import 'services/audio_player_handler.dart';
import 'services/cast_service.dart';
import 'services/player_tuning.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  MediaKit.ensureInitialized();
  await CastService.initialize().catchError((Object error) {
    debugPrint('Google Cast unavailable: $error');
  });

  // Initialize SharedPreferences synchronously
  final prefs = await SharedPreferences.getInstance();

  // The app follows the device language until the user says otherwise.
  // SettingsRepository falls back to 'en' when the key is absent and so
  // cannot tell an untouched install from a deliberate English choice —
  // stamping the sentinel once, here, makes every later read unambiguous.
  if (!prefs.containsKey(languagePrefsKey)) {
    await prefs.setString(languagePrefsKey, systemLanguageCode);
  }

  // The audio handler owns the same Player instance the UI drives, so
  // background playback and the notification stay in sync with the
  // on-screen controls.
  //
  // The stream arrives through the local relay in bounded slices, so mpv
  // needs enough demuxer cache to ride out a slow slice without draining
  // — the 32 MB default is thin for 1080p+ and shows up as periodic
  // stutter. https stays in the whitelist for live broadcasts, which are
  // HLS playlists ffmpeg fetches itself rather than through the relay.
  final player = Player(
    configuration: const PlayerConfiguration(
      bufferSize: 96 * 1024 * 1024,
      protocolWhitelist: [
        'file',
        'tcp',
        'tls',
        'http',
        'https',
        'data',
        'crypto',
      ],
      title: 'BoodTube',
    ),
  );
  await _tunePlayerCache(player, SettingsRepository(prefs).load());

  // Nothing on the way to runApp is allowed to decide whether the app
  // renders. audio_service talks to platform channels that can throw or
  // simply never answer, and awaiting it unguarded turned a background
  // playback problem into a permanently blank screen. Without the
  // handler the app loses the lock screen controls; without runApp it
  // loses everything.
  final audioHandler = await setupAudioService(player)
      .timeout(const Duration(seconds: 10))
      .catchError((Object e) {
    debugPrint('audio service unavailable, continuing without it: $e');
    return SmartTubeAudioHandler(player);
  });

  runApp(
    ProviderScope(
      overrides: [
        sharedPreferencesProvider.overrideWithValue(prefs),
        mediaPlayerProvider.overrideWithValue(player),
        audioHandlerProvider.overrideWithValue(audioHandler),
      ],
      child: const SmartTubeApp(),
    ),
  );
}

/// mpv properties media_kit does not surface through
/// [PlayerConfiguration]. Read-ahead is what actually stops the relay's
/// slice boundaries from being audible; the rest keeps a seek from
/// throwing away everything already buffered.
Future<void> _tunePlayerCache(Player player, AppSettings settings) async {
  final platform = player.platform;
  if (platform is! NativePlayer) return;
  try {
    // Buffer sizes, audio delay and pitch come from the saved tweaks
    // (services/player_tuning.dart), which is also what PlayerController
    // re-applies on every open. Nothing here is a literal any more, so
    // the startup player and a mid-session preset change agree.
    final tuning = playerTuningProperties(
      preset: settings.bufferPreset,
      audioDelayMs: 0,
      keepPitch: settings.keepPitch,
      totalRamBytes: await readDeviceRamBytes(),
    );
    for (final entry in tuning.entries) {
      await platform.setProperty(entry.key, entry.value);
    }
    // Keep what has already been demuxed when the user scrubs backwards.
    await platform.setProperty('demuxer-seekable-cache', 'yes');

    // Live broadcasts are HLS, and YouTube spreads their segments over
    // several CDN hosts. ffmpeg tries to keep one connection alive
    // across them, fails ("Cannot reuse HTTP connection for different
    // host") and stalls after the first segment, so persistent HTTP is
    // off and dropped segments are retried.
    await platform.setProperty(
      'demuxer-lavf-o',
      'seg_max_retry=5,strict=experimental,allowed_extensions=ALL,'
          'http_persistent=0,http_multiple=0,reconnect=1,'
          'reconnect_streamed=1,reconnect_on_network_error=1,'
          'reconnect_delay_max=5,'
          'protocol_whitelist=[file,tcp,tls,http,https,crypto,data]',
    );
  } catch (e) {
    debugPrint('player cache tuning skipped: $e');
  }
}

class SmartTubeApp extends ConsumerWidget {
  const SmartTubeApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(appRouterProvider);
    final settings = ref.watch(settingsControllerProvider);

    return MaterialApp.router(
      title: 'BoodTube',
      debugShowCheckedModeBanner: false,

      // FIXED: Localization delegates
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      // null means "system default": Flutter resolves the device locale
      // against supportedLocales itself, so an Arabic phone opens in
      // Arabic without the user touching settings.
      locale: localeForLanguage(settings.language),

      // Theme
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      themeMode: _mapThemeMode(settings.themeMode),

      // Direction follows the locale automatically once
      // localizationsDelegates are in place — no manual override.

      // Routing
      routerConfig: router,
    );
  }

  /// يحول AppThemeMode (local) إلى Material's ThemeMode
  ThemeMode _mapThemeMode(AppThemeMode mode) {
    switch (mode) {
      case AppThemeMode.system:
        return ThemeMode.system;
      case AppThemeMode.light:
        return ThemeMode.light;
      case AppThemeMode.dark:
        return ThemeMode.dark;
    }
  }
}
