// ============================================================
// SmartTube Mobile - Main Entry Point (FIXED: l10n delegates + AppThemeMode mapping)
// ============================================================

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:media_kit/media_kit.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Generated by flutter_localizations generator
import 'l10n/app_localizations.dart';

import 'data/local/preferences/settings_repository_impl.dart';
import 'presentation/providers/player_providers.dart';
import 'presentation/providers/repository_providers.dart';
import 'presentation/providers/settings_providers.dart';
import 'presentation/routing/app_router.dart';
import 'presentation/theme/app_theme.dart';
import 'services/audio_player_handler.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  MediaKit.ensureInitialized();

  // Initialize SharedPreferences synchronously
  final prefs = await SharedPreferences.getInstance();

  // The audio handler owns the same Player instance the UI drives, so
  // background playback and the notification stay in sync with the
  // on-screen controls.
  //
  // The stream arrives through the local relay in bounded slices, so mpv
  // needs enough demuxer cache to ride out a slow slice without draining
  // — the 32 MB default is thin for 1080p+ and shows up as periodic
  // stutter. https stays in the whitelist for live broadcasts, which are
  // HLS playlists ffmpeg fetches itself rather than through the relay.
  final player = Player(
    configuration: const PlayerConfiguration(
      bufferSize: 96 * 1024 * 1024,
      protocolWhitelist: [
        'file',
        'tcp',
        'tls',
        'http',
        'https',
        'data',
        'crypto',
      ],
      title: 'SmartTube',
    ),
  );
  await _tunePlayerCache(player);
  final audioHandler = await setupAudioService(player);

  runApp(
    ProviderScope(
      overrides: [
        sharedPreferencesProvider.overrideWithValue(prefs),
        mediaPlayerProvider.overrideWithValue(player),
        audioHandlerProvider.overrideWithValue(audioHandler),
      ],
      child: const SmartTubeApp(),
    ),
  );
}

/// mpv properties media_kit does not surface through
/// [PlayerConfiguration]. Read-ahead is what actually stops the relay's
/// slice boundaries from being audible; the rest keeps a seek from
/// throwing away everything already buffered.
Future<void> _tunePlayerCache(Player player) async {
  final platform = player.platform;
  if (platform is! NativePlayer) return;
  try {
    await platform.setProperty('cache', 'yes');
    await platform.setProperty('cache-secs', '60');
    await platform.setProperty('demuxer-readahead-secs', '30');
    // Keep what has already been demuxed when the user scrubs backwards.
    await platform.setProperty('demuxer-seekable-cache', 'yes');
    await platform.setProperty('demuxer-max-back-bytes', '32MiB');

    // Live broadcasts are HLS, and YouTube spreads their segments over
    // several CDN hosts. ffmpeg tries to keep one connection alive
    // across them, fails ("Cannot reuse HTTP connection for different
    // host") and stalls after the first segment, so persistent HTTP is
    // off and dropped segments are retried.
    await platform.setProperty(
      'demuxer-lavf-o',
      'seg_max_retry=5,strict=experimental,allowed_extensions=ALL,'
          'http_persistent=0,http_multiple=0,reconnect=1,'
          'reconnect_streamed=1,reconnect_on_network_error=1,'
          'reconnect_delay_max=5,'
          'protocol_whitelist=[file,tcp,tls,http,https,crypto,data]',
    );
  } catch (e) {
    debugPrint('player cache tuning skipped: $e');
  }
}

class SmartTubeApp extends ConsumerWidget {
  const SmartTubeApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(appRouterProvider);
    final settings = ref.watch(settingsControllerProvider);

    return MaterialApp.router(
      title: 'SmartTube',
      debugShowCheckedModeBanner: false,

      // FIXED: Localization delegates
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      locale: settings.language == 'ar'
          ? const Locale('ar')
          : const Locale('en'),

      // Theme
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      themeMode: _mapThemeMode(settings.themeMode),

      // Direction follows the locale automatically once
      // localizationsDelegates are in place — no manual override.

      // Routing
      routerConfig: router,
    );
  }

  /// يحول AppThemeMode (local) إلى Material's ThemeMode
  ThemeMode _mapThemeMode(AppThemeMode mode) {
    switch (mode) {
      case AppThemeMode.system:
        return ThemeMode.system;
      case AppThemeMode.light:
        return ThemeMode.light;
      case AppThemeMode.dark:
        return ThemeMode.dark;
    }
  }
}
